### ISSUE TITLE
Bug matching types?

### ISSUE THREAD

**Issue by weinbe58** [Roger-luo/Liang.jl#12]
The following doesn't match correctly; maybe I'm doing something wrong?

```Julia
result = @match Float64 begin
           Int => "here"
           Float64 => "there"
end
```
result evaluates to: "here"

**Comment by Roger-luo** [comment]
Ah, I think this is one of the limitations of implementing match as a macro... this is because we are not able to access the scope information of a Julia program, so the single `Symbol` pattern is ambiguous. Consider the following case

```julia
function foo(x, Float64)
   @match x begin
       Int => "here"
       Float64 => "there"
   end
end

foo(1.0, 1.0) # should match what?
```

thus the single `Symbol` pattern is always treated as a variable to dis-ambiguous this semantics. To do what you intended here,
you just need to "quote" the value as if you are quoting it in other Julia expression, e.g


```julia
@match Float64 begin
   $Int => "here"
   $Float64 => "there"
end
```

this was the `&` in MLStyle, but see discussion here https://github.com/thautwarm/MLStyle.jl/issues/160

**Comment by Roger-luo** [comment]
also note that we automatically insert `$` for you in a lot of cases when it's not ambiguous, so this is not a big deal if you find it's working. After thinking a bit more on this, I believe we should add a warning when the pattern variable has a definition in the global scope.

**Comment by Roger-luo** [comment]
Ok this now gives you a warning
